### ISSUE TITLE
Import module issue after updating to latest version

### ISSUE THREAD

**Issue by emilt27** [lmcgartland/graphene-file-upload#24]
There is a traceback: 
```
from graphene_file_upload.django import FileUploadGraphQLView
  File "/usr/local/lib/python3.6/site-packages/graphene_file_upload/django/__init__.py", line 4, in <module>
    from .utils import place_files_in_operations
ModuleNotFoundError: No module named 'graphene_file_upload.django.utils'
```

**Comment by davidroeca** [comment]
Fixed via #25

**Comment by Alegzander** [comment]
Python 3.6 still getting this error:

![image](https://user-images.githubusercontent.com/2426298/58692593-5a0c2300-83a8-11e9-89da-a54c14b252ff.png)

In code module import causes the error.

![image](https://user-images.githubusercontent.com/2426298/58692724-a8212680-83a8-11e9-8ca9-e4478b86af91.png)

**Comment by IngvarListard** [comment]
python 3.7 Django 2.2 same here

**Comment by davidroeca** [comment]
Not able to reproduce. Please post the output of `pip freeze` as well as which minor version of python3.6. As a reference, the following versions worked for me without issue with the [example](https://github.com/lmcgartland/graphene-file-upload/tree/master/examples/django):

Python: `3.6.8`
Packages:
```
aniso8601==6.0.0
Django==2.2.4
graphene==2.1.7
graphene-django==2.5.0
graphene-file-upload==1.2.2
graphql-core==2.2.1
graphql-relay==2.0.0
pkg-resources==0.0.0
promise==2.2.1
pytz==2019.2
Rx==1.6.1
singledispatch==3.4.0.3
six==1.12.0
sqlparse==0.3.0
```

**Comment by mnmistake** [comment]
same issue no one?
